name: Delete ECS Cluster, Prefect ECS Service and ECR repository

on:
  workflow_dispatch:

permissions:
 id-token: write
 contents: read

env:
  PROJECT: realtime-poc

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Delete ECR repository
        continue-on-error: true
        run: |
          aws ecr delete-repository --repository-name ${{ env.PROJECT }} --force
          aws cloudformation delete-stack --stack-name "${{ env.PROJECT }}-ecr"

      - name: Delete ECS agent service
        continue-on-error: true
        run: aws cloudformation delete-stack --stack-name ${{ env.PROJECT }}

      - name: All AWS resources deleted
        run: echo '### All AWS resources deleted! :tada:' >> $GITHUB_STEP_SUMMARY